name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '3 4 * * 5'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint files
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: COUNTRY=us npm run test:integration
        if: always()

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Generate coverage report
        run: npm run coverage:lcov
        if: always()

      - name: Send report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: always()
